# -*- mode: python -*-

block_cipher = None


a = Analysis(['eps_server.py'],
             pathex=['F:\\projekty\\python_photon\\eps'],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
             
             
a.datas += [
('x86\\api-ms-win-core-console-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x86\\api-ms-win-core-console-l1-1-0.dll', 'DLL'),
('x86\\api-ms-win-core-datetime-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x86\\api-ms-win-core-datetime-l1-1-0.dll', 'DLL'),
('x86\\api-ms-win-core-debug-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x86\\api-ms-win-core-debug-l1-1-0.dll', 'DLL'),
('x86\\api-ms-win-core-errorhandling-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x86\\api-ms-win-core-errorhandling-l1-1-0.dll', 'DLL'),
('x86\\api-ms-win-core-file-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x86\\api-ms-win-core-file-l1-1-0.dll', 'DLL'),
('x86\\api-ms-win-core-file-l1-2-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x86\\api-ms-win-core-file-l1-2-0.dll', 'DLL'),
('x86\\api-ms-win-core-file-l2-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x86\\api-ms-win-core-file-l2-1-0.dll', 'DLL'),
('x86\\api-ms-win-core-handle-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x86\\api-ms-win-core-handle-l1-1-0.dll', 'DLL'),
('x86\\api-ms-win-core-heap-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x86\\api-ms-win-core-heap-l1-1-0.dll', 'DLL'),
('x86\\api-ms-win-core-interlocked-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x86\\api-ms-win-core-interlocked-l1-1-0.dll', 'DLL'),
('x86\\api-ms-win-core-libraryloader-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x86\\api-ms-win-core-libraryloader-l1-1-0.dll', 'DLL'),
('x86\\api-ms-win-core-localization-l1-2-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x86\\api-ms-win-core-localization-l1-2-0.dll', 'DLL'),
('x86\\api-ms-win-core-memory-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x86\\api-ms-win-core-memory-l1-1-0.dll', 'DLL'),
('x86\\api-ms-win-core-namedpipe-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x86\\api-ms-win-core-namedpipe-l1-1-0.dll', 'DLL'),
('x86\\api-ms-win-core-processenvironment-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x86\\api-ms-win-core-processenvironment-l1-1-0.dll', 'DLL'),
('x86\\api-ms-win-core-processthreads-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x86\\api-ms-win-core-processthreads-l1-1-0.dll', 'DLL'),
('x86\\api-ms-win-core-processthreads-l1-1-1.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x86\\api-ms-win-core-processthreads-l1-1-1.dll', 'DLL'),
('x86\\api-ms-win-core-profile-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x86\\api-ms-win-core-profile-l1-1-0.dll', 'DLL'),
('x86\\api-ms-win-core-rtlsupport-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x86\\api-ms-win-core-rtlsupport-l1-1-0.dll', 'DLL'),
('x86\\api-ms-win-core-string-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x86\\api-ms-win-core-string-l1-1-0.dll', 'DLL'),
('x86\\api-ms-win-core-synch-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x86\\api-ms-win-core-synch-l1-1-0.dll', 'DLL'),
('x86\\api-ms-win-core-synch-l1-2-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x86\\api-ms-win-core-synch-l1-2-0.dll', 'DLL'),
('x86\\api-ms-win-core-sysinfo-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x86\\api-ms-win-core-sysinfo-l1-1-0.dll', 'DLL'),
('x86\\api-ms-win-core-timezone-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x86\\api-ms-win-core-timezone-l1-1-0.dll', 'DLL'),
('x86\\api-ms-win-core-util-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x86\\api-ms-win-core-util-l1-1-0.dll', 'DLL'),
('x86\\API-MS-Win-core-xstate-l2-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x86\\API-MS-Win-core-xstate-l2-1-0.dll', 'DLL'),
('x86\\api-ms-win-crt-conio-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x86\\api-ms-win-crt-conio-l1-1-0.dll', 'DLL'),
('x86\\api-ms-win-crt-convert-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x86\\api-ms-win-crt-convert-l1-1-0.dll', 'DLL'),
('x86\\api-ms-win-crt-environment-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x86\\api-ms-win-crt-environment-l1-1-0.dll', 'DLL'),
('x86\\api-ms-win-crt-filesystem-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x86\\api-ms-win-crt-filesystem-l1-1-0.dll', 'DLL'),
('x86\\api-ms-win-crt-heap-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x86\\api-ms-win-crt-heap-l1-1-0.dll', 'DLL'),
('x86\\api-ms-win-crt-locale-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x86\\api-ms-win-crt-locale-l1-1-0.dll', 'DLL'),
('x86\\api-ms-win-crt-math-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x86\\api-ms-win-crt-math-l1-1-0.dll', 'DLL'),
('x86\\api-ms-win-crt-multibyte-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x86\\api-ms-win-crt-multibyte-l1-1-0.dll', 'DLL'),
('x86\\api-ms-win-crt-private-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x86\\api-ms-win-crt-private-l1-1-0.dll', 'DLL'),
('x86\\api-ms-win-crt-process-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x86\\api-ms-win-crt-process-l1-1-0.dll', 'DLL'),
('x86\\api-ms-win-crt-runtime-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x86\\api-ms-win-crt-runtime-l1-1-0.dll', 'DLL'),
('x86\\api-ms-win-crt-stdio-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x86\\api-ms-win-crt-stdio-l1-1-0.dll', 'DLL'),
('x86\\api-ms-win-crt-string-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x86\\api-ms-win-crt-string-l1-1-0.dll', 'DLL'),
('x86\\api-ms-win-crt-time-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x86\\api-ms-win-crt-time-l1-1-0.dll', 'DLL'),
('x86\\api-ms-win-crt-utility-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x86\\api-ms-win-crt-utility-l1-1-0.dll', 'DLL'),
('x86\\ucrtbase.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x86\\ucrtbase.dll', 'DLL'),
('x64\\api-ms-win-core-console-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x64\\api-ms-win-core-console-l1-1-0.dll', 'DLL'),
('x64\\api-ms-win-core-datetime-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x64\\api-ms-win-core-datetime-l1-1-0.dll', 'DLL'),
('x64\\api-ms-win-core-debug-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x64\\api-ms-win-core-debug-l1-1-0.dll', 'DLL'),
('x64\\api-ms-win-core-errorhandling-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x64\\api-ms-win-core-errorhandling-l1-1-0.dll', 'DLL'),
('x64\\api-ms-win-core-file-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x64\\api-ms-win-core-file-l1-1-0.dll', 'DLL'),
('x64\\api-ms-win-core-file-l1-2-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x64\\api-ms-win-core-file-l1-2-0.dll', 'DLL'),
('x64\\api-ms-win-core-file-l2-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x64\\api-ms-win-core-file-l2-1-0.dll', 'DLL'),
('x64\\api-ms-win-core-handle-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x64\\api-ms-win-core-handle-l1-1-0.dll', 'DLL'),
('x64\\api-ms-win-core-heap-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x64\\api-ms-win-core-heap-l1-1-0.dll', 'DLL'),
('x64\\api-ms-win-core-interlocked-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x64\\api-ms-win-core-interlocked-l1-1-0.dll', 'DLL'),
('x64\\api-ms-win-core-libraryloader-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x64\\api-ms-win-core-libraryloader-l1-1-0.dll', 'DLL'),
('x64\\api-ms-win-core-localization-l1-2-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x64\\api-ms-win-core-localization-l1-2-0.dll', 'DLL'),
('x64\\api-ms-win-core-memory-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x64\\api-ms-win-core-memory-l1-1-0.dll', 'DLL'),
('x64\\api-ms-win-core-namedpipe-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x64\\api-ms-win-core-namedpipe-l1-1-0.dll', 'DLL'),
('x64\\api-ms-win-core-processenvironment-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x64\\api-ms-win-core-processenvironment-l1-1-0.dll', 'DLL'),
('x64\\api-ms-win-core-processthreads-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x64\\api-ms-win-core-processthreads-l1-1-0.dll', 'DLL'),
('x64\\api-ms-win-core-processthreads-l1-1-1.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x64\\api-ms-win-core-processthreads-l1-1-1.dll', 'DLL'),
('x64\\api-ms-win-core-profile-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x64\\api-ms-win-core-profile-l1-1-0.dll', 'DLL'),
('x64\\api-ms-win-core-rtlsupport-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x64\\api-ms-win-core-rtlsupport-l1-1-0.dll', 'DLL'),
('x64\\api-ms-win-core-string-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x64\\api-ms-win-core-string-l1-1-0.dll', 'DLL'),
('x64\\api-ms-win-core-synch-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x64\\api-ms-win-core-synch-l1-1-0.dll', 'DLL'),
('x64\\api-ms-win-core-synch-l1-2-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x64\\api-ms-win-core-synch-l1-2-0.dll', 'DLL'),
('x64\\api-ms-win-core-sysinfo-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x64\\api-ms-win-core-sysinfo-l1-1-0.dll', 'DLL'),
('x64\\api-ms-win-core-timezone-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x64\\api-ms-win-core-timezone-l1-1-0.dll', 'DLL'),
('x64\\api-ms-win-core-util-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x64\\api-ms-win-core-util-l1-1-0.dll', 'DLL'),
('x64\\api-ms-win-crt-conio-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x64\\api-ms-win-crt-conio-l1-1-0.dll', 'DLL'),
('x64\\api-ms-win-crt-convert-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x64\\api-ms-win-crt-convert-l1-1-0.dll', 'DLL'),
('x64\\api-ms-win-crt-environment-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x64\\api-ms-win-crt-environment-l1-1-0.dll', 'DLL'),
('x64\\api-ms-win-crt-filesystem-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x64\\api-ms-win-crt-filesystem-l1-1-0.dll', 'DLL'),
('x64\\api-ms-win-crt-heap-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x64\\api-ms-win-crt-heap-l1-1-0.dll', 'DLL'),
('x64\\api-ms-win-crt-locale-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x64\\api-ms-win-crt-locale-l1-1-0.dll', 'DLL'),
('x64\\api-ms-win-crt-math-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x64\\api-ms-win-crt-math-l1-1-0.dll', 'DLL'),
('x64\\api-ms-win-crt-multibyte-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x64\\api-ms-win-crt-multibyte-l1-1-0.dll', 'DLL'),
('x64\\api-ms-win-crt-private-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x64\\api-ms-win-crt-private-l1-1-0.dll', 'DLL'),
('x64\\api-ms-win-crt-process-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x64\\api-ms-win-crt-process-l1-1-0.dll', 'DLL'),
('x64\\api-ms-win-crt-runtime-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x64\\api-ms-win-crt-runtime-l1-1-0.dll', 'DLL'),
('x64\\api-ms-win-crt-stdio-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x64\\api-ms-win-crt-stdio-l1-1-0.dll', 'DLL'),
('x64\\api-ms-win-crt-string-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x64\\api-ms-win-crt-string-l1-1-0.dll', 'DLL'),
('x64\\api-ms-win-crt-time-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x64\\api-ms-win-crt-time-l1-1-0.dll', 'DLL'),
('x64\\api-ms-win-crt-utility-l1-1-0.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x64\\api-ms-win-crt-utility-l1-1-0.dll', 'DLL'),
('x64\\ucrtbase.dll', 'C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x64\\ucrtbase.dll', 'DLL')] 

             
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          name='eps_server',
          debug=False,
          strip=False,
          upx=True,
          runtime_tmpdir=None,
          console=True )

          